---
title: "Exercise 2"
author: "Dariusz Kęsicki"
date: "3/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
load("../Data/season_1.RData")
```

# Suits

***

### Overview

Suits is an American legal drama television series created and written by Aaron Korsh. It premiered on USA Network on June 23, 2011, produced by Universal Cable Productions. It concluded on September 25, 2019.

Set at a fictional New York City law firm, it follows Mike Ross (Patrick J. Adams), who uses his eidetic memory to talk his way into a job as an associate working for successful closer Harvey Specter (Gabriel Macht), despite being a college dropout who never attended law school.[1] It focuses on Harvey and Mike winning lawsuits and closing cases, while hiding Mike's secret.[2] It also features Rick Hoffman as neurotic financial lawyer Louis Litt, Meghan Markle as ambitious paralegal Rachel Zane, Sarah Rafferty as Harvey’s legal secretary and confidante Donna Paulsen, and Gina Torres as the firm’s managing partner, Jessica Pearson.

On January 30, 2018, the series was renewed for an eighth season although Torres, Adams and Markle all left the show,[3] with Katherine Heigl joining the cast as Samantha Wheeler. Recurring characters Alex Williams (Dulé Hill) and Katrina Bennett (Amanda Schull) were promoted to series regulars.[4] The show was renewed for a 10-episode ninth and final season on January 23, 2019, which premiered on July 17, 2019.[5][6]

Throughout its run, Suits was nominated for several awards, with Torres and Adams receiving individual praise. Besides two nominations recognizing her role as a supporting actress, Torres was awarded Outstanding Performance in a Television Series at the 2013 NHMC Impact Awards. Adams was nominated for Outstanding Performance by a Male Actor in a Drama Series at the 2012 Screen Actors Guild Awards. The show itself was nominated for two People's Choice Awards. The show's success spawned a short-lived spin-off, Pearson, centered on Jessica Pearson's entry into Chicago politics, which premiered alongside the final season of Suits on July 17, 2019.[7][8][9]

***

### Season 1 summary

Expelled student Mike Ross makes a living illegally taking the Law School Admission Test for others. He decided to start doing this to pay for his grandmother's care. In the show's pilot episode, Mike agrees to deliver a case of marijuana for his best friend Trevor, a drug dealer, for a large payout. Mike astutely avoids being arrested in a sting, only to stumble into a job interview with Harvey Specter, called the best closer in the city. Mike's tenacity and knowledge of the law impress Harvey enough to win him the associate position, even though Mike didn't attend Harvard, a usual prerequisite, and lacks credentials to practice law legally. Together they try cases for the firm Pearson Hardman while maintaining the secret that Mike is a fraud. The first season also introduces us to Mike’s and Rachel’s chemistry. It gives the audience a romantic perspective, creating a parallel storyline throughout the first season.

***

You can see first aried of the episodes changed in Figure 1.

***

Series overview:

| No. in season | Episodes  | First aired  |
|:------        |:-----: |:------:      |
| 1             | 12  | June 23, 2011      |
| 2             | 16 | June 14, 2012      |
| 3             | 16 | July 16, 2013      |
| 4            | 16 | June 11, 2014       |
